use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

abstract_target 'PlayKit' do
    
    pod 'PlayKit', :path => '../../playkit-ios'
    pod 'PlayKit/YouboraPlugin', :path => '../../playkit-ios'
    pod 'PlayKit/PhoenixPlugin', :path => '../../playkit-ios' 
    pod 'PlayKit/KalturaStatsPlugin', :path => '../../playkit-ios'
    pod 'PlayKit/KalturaLiveStatsPlugin', :path => '../../playkit-ios'
    pod 'PlayKit/GoogleCastAddon', :path => '../../playkit-ios'
    target 'PlayKit_Example' do
    end
    
    target 'PlayKit_Tests' do
        pod 'Quick', '1.1.0'
        pod 'Nimble', '6.0.1'
    end
    
end

pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end

post_install do |installer| 
    installer.pods_project.targets.each do |target| 
        target.build_configurations.each do |config| 
            config.build_settings['SWIFT_VERSION'] = '3.0'
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
        end 
    end 
end
