use_frameworks!

target 'PlayKit_Example' do
    pod 'PlayKit', :path => '../'
    pod 'PlayKit/IMAPlugin', :path => '../'
    pod 'PlayKit/YouboraPlugin', :path => '../'
end  
target 'PlayKit_Tests' do
    #inherit! :search_paths
    pod 'PlayKit', :path => '../'
    pod 'PlayKit/IMAPlugin', :path => '../'
    pod 'PlayKit/YouboraPlugin', :path => '../'
end
pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end

post_install do |installer| 
    installer.pods_project.targets.each do |target| 
        target.build_configurations.each do |config| 
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO' 
        end 
    end 
end
