use_frameworks!

target 'PlayKit_Example' do
    pod 'PlayKit', :path => '../../playkit-ios'
    pod 'PlayKit/IMAPlugin', :path => '../../playkit-ios'
    pod 'PlayKit/YouboraPlugin', :path => '../../playkit-ios'

    target 'PlayKit_Tests' do
    end
end  

pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end

post_install do |installer| 
    installer.pods_project.targets.each do |target| 
        target.build_configurations.each do |config| 
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO' 
        end 
    end 
end
