# Uncomment the next line to define a global platform for your project
platform :tvos, '9.0'

target 'tvOSTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'PlayKit', :path => '..'

end
