# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TestApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestApp
  pod 'PlayKit', :path => '..'
  pod 'PlayKit/PhoenixPlugin', :path => '..'
  pod 'PlayKit/KalturaStatsPlugin', :path => '..'
  pod 'PlayKit/KalturaLiveStatsPlugin', :path => '..'

end

pre_install do |installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
