# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

def sharedPods
  pod 'PlayKit', :path => '..'
  #pod 'KalturaNetKit'#, :path => '../../netkit-ios'
  #pod 'PlayKitUtils'#, :path => '../../playkit-ios-utils'
end

target 'TestApp_v4_2' do
  sharedPods
end

target 'TestApp_v5' do
  sharedPods
end
