# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

abstract_target 'SharedPods' do

    # Pods for TestApp
    pod 'PlayKit', :path => '..'
    
    target 'TestApp'

end
