name: CI

on:
  push:
    branches: [ "develop" ]
    paths-ignore:
      - 'docs/**'
      - 'iOSTestApp/**'
      - 'tvOSTestApp/**'
      - 'Example/**'
      - 'TestApp/**'
      - 'LICENSE'
      - '*.md'
      
concurrency: 
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    name: "CocoaPods update"
    runs-on: macOS-12

    steps:
    - uses: actions/checkout@v3

    - name: Updating CocoaPods
      run: gem install cocoapods

  build:
    name: "CocoaPods linting"
    runs-on: macOS-12

    steps:
    - uses: actions/checkout@v3

    - name: Updating CocoaPods repo
      run: pod repo update

    - name: Pod linting
      run: pod lib lint --fail-fast --verbose --allow-warnings

  SPM:
    name: "Build SPM"
    runs-on: macOS-12
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - destination: "OS=16.2,name=iPhone 14 Pro"
            name: "iOS"
            scheme: "PlayKit-Package"
          - destination: "OS=16.0,name=Apple TV"
            name: "tvOS"
            scheme: "PlayKit-Package"
    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.name }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme "${{ matrix.scheme }}" -destination "${{ matrix.destination }}" clean test | xcpretty
        
