name: PR

on:
  pull_request:
    branches: [ "develop" ]
    paths-ignore:
            - 'docs/**'
            - 'iOSTestApp/**'
            - 'tvOSTestApp/**'
            - 'Example/**'
            - 'TestApp/**'
            - 'LICENSE'
            - '*.md'

concurrency:
    group: PR_${{ github.head_ref }}
    cancel-in-progress: true

jobs:
  build:
    name: "CocoaPods linting"
    environment: PR
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3

      - name: Updating Cocoapods
        run: gem install cocoapods

      - name: Updating CocoaPods repo
        run: pod repo update

      - name: Pod linting
        run: pod lib lint --fail-fast --verbose --allow-warnings
      
  SPM:
    name: "Build SPM"
    environment: PR
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        include:
          - destination: "OS=16.2,name=iPhone 14 Pro"
            name: "iOS"
            scheme: "PlayKit-Package"
          - destination: "OS=16.2,name=Apple TV"
            name: "tvOS"
            scheme: "PlayKit-Package"
    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.name }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme "${{ matrix.scheme }}" -destination "${{ matrix.destination }}" clean test | xcpretty
        
        
